title: Geomad
description: Leading the Future of Agriculture with Advanced Remote Sensing Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geomads.github.io" # the base hostname & protocol for your site
markdown: kramdown
theme: minima # or any theme you prefer

# Build settings
plugins:
  - jekyll-feed
